First, let's do a "hello world" print.

In [ ]:
# Hello World

print("Hello World!")

Hello World!


In [ ]:
# Integer
myint = 7
print(myint)

7


In [ ]:
# Float
myfloat = 7.
print(myfloat)

7.0


In [ ]:
# String
mystring = "hello"
print(mystring)

hello


In [ ]:
# Simple operation
a = 1
b = 2
c = a + b
print(c)

aa = "Hello "
bb = "World!"
cc = aa + bb
print(cc)

3
Hello World!


In [ ]:
mylist = []
mylist.append(1)
mylist.append(2)
mylist.append(3.)
mylist.append("hello")
# Can be of different types
print(mylist)
print(mylist[2])
mylist2 = [4, 5, 6]
print(mylist2)

[1, 2, 3.0, 'hello']
3.0
[4, 5, 6]


List is mutable, which means you can modify its elements

In [ ]:
mylist[2] = 10
print(mylist)

[1, 2, 10, 'hello']


Tuple is like list. But it is immutable

In [ ]:
mytuple = (1,2,3)
print(mytuple[2])

3


In [ ]:
# You should see an error
mytuple[2] = 5

TypeError: 'tuple' object does not support item assignment

In [ ]:
number = 1 + 2 * 3 / 4.0
print(number)

2.5


In [ ]:
remainder = 11 % 3
print(remainder)

2


In [ ]:
squared = 7 ** 2
cubed = 2 ** 3
print(squared)
print(cubed)

49
8


Basic String Operations

In [ ]:
helloworld = "hello" + " " + "world"
print(helloworld)

hello world


In [ ]:
lotsofhellos = "hello" * 10
print(lotsofhellos)

hellohellohellohellohellohellohellohellohellohello


List Operations

In [ ]:
even_numbers = [2,4,6,8]
odd_numbers = [1,3,5,7]
all_numbers = odd_numbers + even_numbers
print(all_numbers)

[1, 3, 5, 7, 2, 4, 6, 8]


In [ ]:
print([1,2,3] * 3)

[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [ ]:
name = "John"
print("Hello, %s!" % name)

Hello, John!


In [ ]:
name = "John"
age = 23
print("%s is %d years old." % (name, age))

John is 23 years old.


In [ ]:
mylist = [1,2,3]
print("A list: %s" % mylist)

A list: [1, 2, 3]


In [ ]:
myfloat = 2.0
print("3 digit precision: %.3f" % myfloat)

3 digit precision: 2.000


In [ ]:
astring = "Hello world!"
print(len(astring)) # Length of string

12


In [ ]:
print(astring.index('l')) # Show the index of the first occurance of the patttern

2


In [ ]:
print(astring.count("l")) # Count the number of occurences

3


In [ ]:
print(astring[3:7]) # Subindex

lo w


In [ ]:
print(astring[:-1]) # Exclude the last character

Hello world


In [ ]:
print(astring[::-1]) # Reverse

!dlrow olleH


In [ ]:
print(astring.upper()) # Upper case

HELLO WORLD!


In [ ]:
print(astring.lower()) # lower case

hello world!


In [ ]:
# Check conditions and return a boolean value (Boolean values can only be True and False)
print(astring.startswith("Hello"))
print(astring.endswith("NO"))

True
False


In [ ]:
alist = astring.split(" ") # Split the string using the pattern and turn parts to a list
print(alist)

['Hello', 'world!']


Conditions

and: True and True is True; True and False is False; False and True is False; False and False is False

or: True or True is True; True or False is True; False or True is True; False or False is False

not: Not True is False; Not False is True

In [ ]:
print(1 < 2)
print(1 <= 2)
print(1 == 2)
print(1 + 2 >= 5)

True
True
False
False


In [ ]:
name = "John"
age = 23

if name == "John" and age == 23:
    print("My name is john and I'm 23 years old")
else:
    print("Should not print")

if name == "John" or age == 24:
    print("My name is john or I'm 24 years old")
else:
    print("Should not print")

My name is john and I'm 23 years old
My name is john or I'm 24 years old


In [ ]:
if name in ["John", "Nick", "David"]:
    print("My name is one of John, Nick, and David")

My name is one of John, Nick, and David


In [ ]:
x = [1, 2, 3]
y = [1, 2, 3]
print(x==y) # Check the values
print(x is y) # Check if x and y are the same instance. They are not because they are two objects instantiated at different locations in memory
z = x
print(x is z)

True
False
True


In [ ]:
x[0] = 123
print(x, y, z)
# Think why you see this behavior:
# x does not change because it's a different instance. z also changes because z and x points to the same instance.

[123, 2, 3] [1, 2, 3] [123, 2, 3]


In [ ]:
for number in [1,2,3,4,5]:
    print(number)

1
2
3
4
5


In [ ]:
for char in "Hello Worlds":
    print(char)

H
e
l
l
o
 
W
o
r
l
d
s


In [ ]:
for x in range(5): # Start from 0. Does not include 5.
    print(x)

0
1
2
3
4


In [ ]:
for x in range(3,6): # Include 3 but not 6.
    if x % 2 == 0:
        continue # Does not print even number and continues to next iteration in the loop
    print(x)

3
5


In [ ]:
for x in range(3,8,2):
  # iterate from 3 to 7 with interval 2
    print(x)

3
5
7


In [ ]:
count = 0
while count < 5:
    if count == 4:
        print("We break at 4")
        break # Break the loop
    print(count)
    count += 1

0
1
2
3
We break at 4


In [ ]:
def my_function(x):
    print("This function prints out %s" % x)

In [ ]:
my_function(3)

This function prints out 3


In [ ]:
def sum_two_numbers(number1, number2):
    return number1 + number2

In [ ]:
sum_two_numbers(3,6)

9

In [ ]:
print(number1) # Should error out because number1 is local to the function, not outside the function

NameError: name 'number1' is not defined

In [ ]:
class MyClass:
    def __init__(self, number):
      #__init__ is called when the class object is instantiated
        self.number = number

    def print_number(self):
      # This is a class method that you can call on the object
        print(self.number)

In [ ]:
myObject1 = MyClass(2)
myObject2 = MyClass(3)
myObject1.print_number()
myObject2.print_number()

2
3


In [ ]:
phonebook = {}
phonebook["John"] = 938477566
phonebook["Jack"] = 938377264
phonebook["Jill"] = 947662781
print(phonebook)

{'John': 938477566, 'Jack': 938377264, 'Jill': 947662781}


In [ ]:
# Iterate over dictionaries. Can access both key and value at the same time using .items()
for name, number in phonebook.items():
    print("Phone number of %s is %d" % (name, number))

Phone number of John is 938477566
Phone number of Jack is 938377264
Phone number of Jill is 947662781


In [ ]:
phonebook.pop("John")

938477566

In [ ]:
print(phonebook)

{'Jack': 938377264, 'Jill': 947662781}


Python Packages are libraries written by other people that we can use, so that we do not need to reinvent the wheels.

Common packages used in data science and machine learning are numpy, pandas, scikit-learn, matplotlib. We will be using those packages through the project

numpy: array and matrix operations<br>
pandas: dataframe operations<br>
scikit-learn: machine learning algorithms and methods<br>
matplotlib: plotting and visualization

In [ ]:
# In order to use the package, you need to import it first
import numpy as np
import pandas as pd

In [ ]:
array1 = np.array([1,2,3,4,5])
array2 = np.array([5,6,7,8,9])
print(array1)
print(array2)

[1 2 3 4 5]
[5 6 7 8 9]


Unlike python native list, numpy array are operations are element wise.

In [ ]:
print(array1+array2)
print(array1*array2)

[ 6  8 10 12 14]
[ 5 12 21 32 45]


In [ ]:
# Create a random matrix
matrix1 = np.random.rand(10,5)

In [ ]:
array3 = np.matmul(matrix1, array1) # Help you refresh matrix multiplication

In [ ]:
array3.shape

(10,)

In [ ]:
df = pd.DataFrame(matrix1, columns=[f"column_{i}" for i in range(5)])

In [ ]:
df # look at the whole dataframe

column_0  column_1  column_2  column_3  column_4
0  0.971994  0.789351  0.728234  0.005595  0.186820
1  0.237673  0.604880  0.324096  0.091408  0.481241
2  0.765176  0.759911  0.087544  0.453530  0.556648
3  0.144095  0.714509  0.435265  0.848145  0.131360
4  0.973089  0.392950  0.347617  0.390760  0.242740
5  0.760450  0.293896  0.592996  0.879684  0.735180
6  0.547269  0.718498  0.035491  0.879638  0.738326
7  0.924736  0.715271  0.818818  0.836495  0.911996
8  0.625476  0.620168  0.179243  0.607017  0.312558
9  0.871206  0.096587  0.624462  0.306618  0.775899

In [ ]:
df["column_0"] # Look at one column

0    0.971994
1    0.237673
2    0.765176
3    0.144095
4    0.973089
5    0.760450
6    0.547269
7    0.924736
8    0.625476
9    0.871206
Name: column_0, dtype: float64

In [ ]:
df["column_6"] = df["column_0"] + df["column_1"] # Create a new column based on two existing columns

In [ ]:
df

column_0  column_1  column_2  column_3  column_4  column_6
0  0.971994  0.789351  0.728234  0.005595  0.186820  1.761345
1  0.237673  0.604880  0.324096  0.091408  0.481241  0.842553
2  0.765176  0.759911  0.087544  0.453530  0.556648  1.525087
3  0.144095  0.714509  0.435265  0.848145  0.131360  0.858605
4  0.973089  0.392950  0.347617  0.390760  0.242740  1.366039
5  0.760450  0.293896  0.592996  0.879684  0.735180  1.054346
6  0.547269  0.718498  0.035491  0.879638  0.738326  1.265767
7  0.924736  0.715271  0.818818  0.836495  0.911996  1.640007
8  0.625476  0.620168  0.179243  0.607017  0.312558  1.245644
9  0.871206  0.096587  0.624462  0.306618  0.775899  0.967794

In [ ]:
df.describe() # Calculate the statistics for each column

column_0   column_1   column_2   column_3   column_4   column_6
count  10.000000  10.000000  10.000000  10.000000  10.000000  10.000000
mean    0.682116   0.570602   0.417377   0.529889   0.507277   1.252719
std     0.295285   0.231816   0.270131   0.331346   0.278148   0.323185
min     0.144095   0.096587   0.035491   0.005595   0.131360   0.842553
25%     0.566821   0.445933   0.215456   0.327654   0.260195   0.989432
50%     0.762813   0.667338   0.391441   0.530274   0.518944   1.255705
75%     0.911353   0.717691   0.616596   0.845233   0.737539   1.485325
max     0.973089   0.789351   0.818818   0.879684   0.911996   1.761345